PROJECT_NAME      = hermes3d
# input
INPUT             = \
	${PROJECT_SOURCE_DIR}/src \
	${PROJECT_SOURCE_DIR}/common \
	${PROJECT_SOURCE_DIR}/examples
FILE_PATTERNS     = *.cc *.h
RECURSIVE         = YES
EXCLUDE_PATTERNS  = */examples/*.h */src/shapeset/*tetrad?.cc
SEARCHENGINE      = YES

GENERATE_LATEX   = NO
GENERATE_MAN     = NO
GENERATE_RTF     = NO
CASE_SENSE_NAMES = NO
GENERATE_HTML    = NO
GENERATE_XML     = YES

FULL_PATH_NAMES   = YES
STRIP_FROM_PATH   = ${PROJECT_SOURCE_DIR}
STRIP_FROM_INC_PATH = ${PROJECT_SOURCE_DIR}

EXAMPLE_PATH      = ${PROJECT_SOURCE_DIR}/examples
EXAMPLE_RECURSIVE = YES
EXAMPLE_PATTERNS  = *.cc

# output
OUTPUT_DIRECTORY     = ${PROJECT_BINARY_DIR}/doc
JAVADOC_AUTOBRIEF    = YES
QUIET                = NO
WARNINGS             = NO
WARN_IF_DOC_ERROR    = NO
WARN_IF_UNDOCUMENTED = NO
WARN_NO_PARAMDOC     = NO

ALPHABETICAL_INDEX   = YES
